### ISSUE TITLE
nv21怎么转换成ncnn::mat

### ISSUE THREAD

**Issue by ivoxx** [Tencent/ncnn#1033]
我这样操作的：
jbyterArray Nv21_ = ...
jbyte *Nv21 = env->GetByteArrayElements(Nv21_, NULL);
    
unsigned char* rgb = new unsigned char[Width * Height *3];
const unsigned char* UncharNv21 = (unsigned char*)Nv21;
ncnn::yuv420sp2rgb(UncharNv21, Width, Height, rgb);

ncnn::Mat ncnn_img;
ncnn_img = ncnn::Mat::from_pixels(rgb, ncnn::Mat::PIXEL_BGR2RGB,Width, Height);
这样操作好像有问题，应该怎么操作？

**Comment by nihui** [comment]
android 摄像头的数据可能需要旋转 270/90

**Comment by soham24** [comment]
@ivoxx  I have a solution where I rotate it with use of opencv .
I 


 cv::Mat grayMat = cv::Mat(height, width, CV_8UC1, (unsigned char*)b_data);
    if(rotation == 90)
    {
        rotateMat(grayMat, 1);
    }
    else if(rotation == 180) {
        rotateMat(grayMat, 3);


    }
    else if(rotation == 270 || rotation == -90) {
        rotateMat(grayMat, 2);
    }

 ncnn::Mat ncnn_img;

//here I am converting gray to rgb because my model expects rgb image. you should do whatever required.
 ncnn_img = ncnn::Mat::from_pixels(bgrMat.data, ncnn::Mat::PIXEL_GRAY2RGB,
                                          bgrMat.cols, bgrMat.rows);


And here is rotatemat function
void rotateMat(cv::Mat &matImage, int rotFlag) {
    //1=ClockWise
    //2=CounterClockWise
    //3=180degree
    if(rotFlag == 1) {cv::transpose(matImage, matImage);cv::flip(matImage, matImage, 1);}
    else if(rotFlag == 2) {cv::transpose(matImage, matImage);cv::flip(matImage, matImage, 0);}
    else if(rotFlag == 3) {cv::flip(matImage, matImage, -1);}
}


@nihui  can we eliminate this opencv conversion and rotate mat directly.?
