### ISSUE TITLE
Different inference result between given NCNN yolov3 model and converted yolov3 model

### ISSUE THREAD

**Issue by WeiyiLi** [Tencent/ncnn#1289]
Hi,
I am trying to conduct the inference for the mobilenetv2 yolov3 lite model, which is introduced in yolov3.cpp. 

I tried the given models in https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp#L43 and https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp#L44. Additionally, I converted another version of this model from https://github.com/eric612/MobileNet-YOLO/tree/master/models/mobilenetv2_voc/yolo_lite. (I used yolov3_m2 model, which has the same architecture as the given model except the confidence_threshold in YOLOV3DetectionOutput is different). However, the converted model produced different result from the given model. 

I dumped the feature map for each layer and found the output is different starting from the first convolution. So I guess the weight data (.bin file) is changed??? If so, the mAP might not be the same as reported. 

Does anyone encounter the same issue as me? Or did I do anything wrong in the conversion? Thanks!

**Comment by eric612** [comment]
I forgot to update weight in this repo. , please see this compare page
I had update a new weights at 8/7 which increased a little mAP , because of different training iters. 

https://github.com/eric612/MobileNet-YOLO/commit/a7b7059199711b244f46dc159d8406ef7d1be24e#diff-1d9d337437dc387ec70953e7baa33a38

https://github.com/eric612/MobileNet-YOLO/commit/63f38b7be1a0be8c1117a5fbada949e525939add#diff-1d9d337437dc387ec70953e7baa33a38

I will update it later , thanks a lot

**Comment by WeiyiLi** [comment]
@eric612 Thanks for the response. So the given NCNN model in https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp#L43 and https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp#L44 is out of date, right?

**Comment by nihui** [comment]
hi, you can retrieve the converted ncnn models from https://github.com/nihui/ncnn-assets/tree/master/models
