### ISSUE TITLE
Support which detection network model,Faster-RCNN or SSD or YOLO?

### ISSUE THREAD

**Issue by BUG1989** [Tencent/ncnn#152]
I find the caffe2ncnn tools did not support the SSD model.
So in the detection application,Which model has been supported?
Thanks a lots !

**Comment by nihui** [comment]
none of these are supported at the moment
todo priority = ssd > yolo > faster-rcnn

**Comment by nihui** [comment]
ssd implemented

**Comment by nihui** [comment]
faster-rcnn implemented

proposal layer is slightly different from the original py-faster-rcnn implementation
1. top blob is 4 (xmin, ymin, xmax, ymax) * num_roi instead of 5 (N, xmin, ymin, xmax, ymax) * num_roi because N always equals to zero in inference phase
2. ncnn do not support the fourth dim N, so manual loop over rois is needed to extract each bbox regression and classification scores

a faster-rcnn sample will be coming soon

**Comment by nihui** [comment]
mobilnet ssd and faster-rcnn sample are ready

**Comment by bayesianio** [comment]
Dear Team, 
Is Mask-RCNN supported? If not, what do I have to do in order to do it from scratch. 
Thanks,

**Comment by nihui** [comment]
yolov2 implemented
yolov2 sample is ready

yolodetectionoutput layer is slightly different from the original caffe-yolov2 implementation

1.  top blob is 6 (class-id, score, xmin, ymin, xmax, ymax) * num_detected instead of 7 (N, class-id, score, xmin, ymin, xmax, ymax) * num_detected because N always equals to zero in inference phase

**Comment by sebastianfelipe** [comment]
It would be very useful to have some Mask RNCNN as an example. Will be some support to that in the short term? Thanks.

**Comment by zhedasuiyuan** [comment]
> faster-rcnn implemented
> 
> proposal layer is slightly different from the original py-faster-rcnn implementation
> 
> 1. top blob is 4 (xmin, ymin, xmax, ymax) * num_roi instead of 5 (N, xmin, ymin, xmax, ymax) * num_roi because N always equals to zero in inference phase
> 2. ncnn do not support the fourth dim N, so manual loop over rois is needed to extract each bbox regression and classification score
> 
> a faster-rcnn sample will be coming soon

Hi, the sample code is very useful. Thanks! By the way, do you have any plans to improve the second step? It is a little bit weird to loop over each ROI again to check the scores and probs for the classes.  Not sure how much slower it would be with the current design. Any ideas?
