### ISSUE TITLE
ncnn speed compare

### ISSUE THREAD

**Issue by wl3b10s** [Tencent/ncnn#271]
i test standard squeezenet v1.1 on 8xA53 ubuntu 16.04.

i test three kind of implementation.
1. ncnn by default cmake make
2. amazon nnvm+tvm
3. caffe + openblas + handcoded asm

all of them is compiled natively on device. and the time test result show that ncnn is the slowest.

frame test time result
1. ncnn 960ms
2. amazon nnvm + tvm: 360ms
3. caffe+openblas+asm: 200ms

so . is there some tips for optimize speed  for usage of ncnn? thanks.

**Comment by nihui** [comment]
you may need to change the condition to TRUE to build the arm optimized code on ARM Linux, otherwise the slow naive C implementation will be used.
Currently, the optimized code is enabled for android and ios.

https://github.com/Tencent/ncnn/blob/5ff6a1808a91c0770b813c60fe5846225011cba1/src/CMakeLists.txt#L40

**Comment by wl3b10s** [comment]
that is it...

**Comment by yxchng** [comment]
@wl3b10s what speed do you get after the conversion?

**Comment by quocnhat** [comment]
> @wl3b10s what speed do you get after the optimisation?

+1
