### ISSUE TITLE
can not save an image with elempack = 1 (3 works fine) with stbi_image_write (png image).

### ISSUE THREAD

**Issue by thancaocuong** [Tencent/ncnn#4733]
## detail | 详细描述 | 詳細な説明
this code works fine
```
unsigned char* pixeldata; // loaded pixel data
int c = 3;
ncnn::Mat out = ncnn::Mat(w, h, (void*) pixeldata, (size_t)c, c);
stbi_write_png(out_str_elempack1.c_str(), out.w, out.h, out.elempack, out.data, 0);
```
But when I use convert_packing to convert the out Mat, the saved image looks weird
```
ncnn::convert_packing(out, out, 1);
stbi_write_png(out_str_elempack1.c_str(), out.w, out.h, out.elempack, out.data, 0); // does not work
```
So could you help me to properly convert the packing and retain the same shape of W and H?

**Comment by nihui** [comment]
convert mat to pixel data first via `out.to_pixels`

then pass the pixels to stbi_write_png

**Comment by thancaocuong** [comment]
@nihui  you mean after convert packing, I need to replace out.data to the pixels getting from out.to_pixels function? right?

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-opencv#ncnn-to-opencv

refer ncnn::Mat 3 channel -> cv::Mat CV_8UC3 sections

**Comment by thancaocuong** [comment]
@nihui I have changed to the following code. But still can not save the image
```
ncnn::convert_packing(out, out, 1);
unsigned char* out_pixels;
out_pixels = (unsigned char *) malloc(out.w * out.h * out.elempack);
out.to_pixels(out_pixels, ncnn::Mat::PIXEL_RGB);
stbi_write_png(outputpath.c_str(), out.w, out.h, out.elempack, out_pixels, 0);
```

**Comment by thancaocuong** [comment]
I think there might be the problem. When I save the image with WxHx1 and elempack = 3. This function works fine. But when saving image with elempack = 1, It does not work as expected. Also when I call ```ncnn::convert_packing(out, out, 1);``` the w and h of out mat has change. 
```
# original out image
out.w: 1080 out.h 784 out.elempack 3
# after convert_packing out image
out.w: 1080 out.h 2352 out.elempack 1
```

**Comment by nihui** [comment]
The data type required by stbi_write_png is uchar, and the layout is RGBRGBRGB.... This is the conventional pixel data layout

Usually the data type stored in ncnn Mat is float, assuming three channels, the layout is RRRR...GGGG...BBBB...

If you need to convert pixel data to Mat for input to neural network inference, you need to use Mat from_pixels

If you need to convert the output Mat of neural network reasoning back to pixel data, you need to use Mat to_pixels

convert_packing is usually not necessary, because the input and output of ncnn neural networks are usually always without packing layout

**Comment by thancaocuong** [comment]
@nihui  thank you for your valueable comment. I think it works now.
