### ISSUE TITLE
What is full name of project?

### ISSUE THREAD

**Issue by MrMarvel** [Tencent/ncnn#5507]
## What is NCNN meaning?

**Comment by wzyforgit** [comment]
Translate from https://github.com/Tencent/ncnn/blob/master/docs/Home.md#faq
ncnn is full name.
"cnn" means convolutional neural network.
The first "n" have more than one meaning: owner's name "nihui", new (Because there was almost no open source inference framework when ncnn project created), naive (ncnn is implementation), neon (ncnn project created for mobile phone at first time)

**Comment by MrMarvel** [comment]
Thanks for full answer
